### ISSUE TITLE
Could you share results?

### ISSUE THREAD

**Issue by azmathmoosa** [naritapandhe/Gender-Age-Classification-CNN#2]
Could you share your accuracy and validation graphs in the readme file.  I am looking for a good model that I could port to [dlib](http://dlib.net/) DNN.  I need something as a reference to check if I am able to reproduce tested results.  The link in the end is dead.
Thanks.  Good work, BTW.

**Comment by naritapandhe** [comment]
Thanks for pointing out the deadlink.
You can refer this one: https://github.com/naritapandhe/Gender-Age-Classification-CNN/issues/3
